spring:
  application:
    name: msavaliadorcredito

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid} # Usando o mesmo UUID para Eureka
