spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: msmicroservices
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/msmicroservices
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/msmicroservices

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://ms-microservicos-eureka:adm123@localhost:8761/eureka
